version: "3"
services:

    mysql:
      container_name: mysql-service
      ports:
        - "3306:3306"
      restart: always
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: '1234root' # TODO: Change this
        MYSQL_USER: 'root'
        MYSQL_PASS: '1234root'
      volumes:
        - ./volumes/mysql-volume:/var/lib/mysql # path para disco do glusterFS
      networks:
        - docker-network


    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq-service
      ports:
          - 5672:5672
          - 15672:15672
      volumes:
          - ./volumes/rabbitmq-volume/data/:/var/lib/rabbitmq/ # path para disco do glusterFS
          - ./volumes/rabbitmq-volume/log/:/var/log/rabbitmq # path para disco do glusterFS
      networks:
        - docker-network


    api-gateway:
      container_name: api-gateway
      image: leandrocosta1614/gama-apigateway:latest
      ports:
          - 8080:8080
      deploy:
        replicas: 2
        placement:
          max_replicas_per_node: 1
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: on-failure
      networks:
          - docker-network

    product-service:
      container_name: product-service
      image: leandrocosta1614/gama-product-service:latest
      ports:
        - 8081:8080
      depends_on:
        - mysql-service
        - rabbitmq-service
      deploy:
        replicas: 2
        placement:
          max_replicas_per_node: 1
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: on-failure
      networks:
          - docker-network

    order-service:
      container_name: order-service
      image: leandrocosta1614/gama-order-service:latest
      ports:
        - 8082:8080
      depends_on:
        - mysql-service
        - rabbitmq-service
      deploy:
        replicas: 1
        placement:
          max_replicas_per_node: 1
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: on-failure
      networks:
          - docker-network

    inventory-service:
      container_name: inventory-service
      image: leandrocosta1614/gama-inventory-service:latest
      ports:
        - 8083:8080
      depends_on:
        - mysql-service
        - rabbitmq-service
      deploy:
        replicas: 1
        placement:
          max_replicas_per_node: 1
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: on-failure
        networks:
            - docker-network

    review-service:
      container_name: review-service
      image: leandrocosta1614/gama-review-service:latest
      ports:
        - 8084:8080
      depends_on:
        - mysql-service
        - rabbitmq-service
      deploy:
        replicas: 1
        placement:
          max_replicas_per_node: 1
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: on-failure
      networks:
          - docker-network

    shoppingcart-service:
      container_name: shoppingcart-service
      image: leandrocosta1614/gama-shoppingcart-service:latest
      ports:
        - 8085:8080
      depends_on:
        - mysql-service
        - rabbitmq-service
      deploy:
        replicas: 1
        placement:
          max_replicas_per_node: 1
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: on-failure
        networks:
            - docker-network

    user-service:
      container_name: user-service
      image: leandrocosta1614/gama-user-service:latest
      ports:
        - 8086:8080
      depends_on:
        - mysql-service
        - rabbitmq-service
      deploy:
        replicas: 1
        placement:
          max_replicas_per_node: 1
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: on-failure
      networks:
          - docker-network

    promotion-service:
      container_name: promotion-service
      image: leandrocosta1614/gama-promotion-service:latest
      ports:
        - 8087:8080
      depends_on:
        - mysql-service
        - rabbitmq-service
      deploy:
        replicas: 1
        placement:
          max_replicas_per_node: 1
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: on-failure
      networks:
          - docker-network

    payment-service:
      container_name: payment-service
      image: leandrocosta1614/gama-payment-service:latest
      ports:
        - 8088:8080
      depends_on:
        - mysql-service
        - rabbitmq-service
      deploy:
        replicas: 1
        placement:
          max_replicas_per_node: 1
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: on-failure
      networks:
          - docker-network

networks:
  docker-network:
    driver: bridge

  
